version: "3.8"

services:
  criptabot:
    build: .
    container_name: criptabot
    restart: unless-stopped
    env_file:
      - .env                # TG_TOKEN, CHAT_ID, интервалы…
    volumes:
      - ./data:/app/data    # SQLite наружу
      - ./logs:/app/logs    # лог-файлы наружу
    # optional: ограничить память/CPU
    # deploy:
    #   resources:
    #     limits:
    #       memory: 512M
    # healthcheck (aiogram сам упадёт, если токен неверен)
